-- Inserir dados na tabela UF
INSERT INTO tbl_Uf (Nome, Sigla) VALUES ('Acre', 'AC');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Alagoas', 'AL');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Amapá', 'AP');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Amazonas', 'AM');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Bahia', 'BA');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Ceará', 'CE');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Distrito Federal', 'DF');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Espírito Santo', 'ES');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Goiás', 'GO');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Maranhão', 'MA');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Mato Grosso', 'MT');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Mato Grosso do Sul', 'MS');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Minas Gerais', 'MG');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Pará', 'PA');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Paraíba', 'PB');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Paraná', 'PR');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Pernambuco', 'PE');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Piauí', 'PI');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Rio de Janeiro', 'RJ');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Rio Grande do Norte', 'RN');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Rio Grande do Sul', 'RS');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Rondônia', 'RO');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Roraima', 'RR');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Santa Catarina', 'SC');
INSERT tbl_Uf (Nome, Sigla) VALUES ('São Paulo', 'SP');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Sergipe', 'SE');
INSERT tbl_Uf (Nome, Sigla) VALUES ('Tocantins', 'TO');
